# Generated by Django 3.1.7 on 2021-06-03 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.hospital')),
                ('oxygen_beds_total', models.IntegerField(default=0)),
                ('oxygen_bed_available', models.IntegerField(default=0)),
                ('oxygen_cylinder_total', models.IntegerField(default=0)),
                ('oxygen_cylinder_available', models.IntegerField(default=0)),
                ('ventilator_total', models.IntegerField(default=0)),
                ('ventilator_available', models.IntegerField(default=0)),
            ],
        ),
    ]
